### ISSUE TITLE
pysyncon -> error in ATT estimate

### ISSUE THREAD

**Issue by arasala** [sdfordham/pysyncon#54]
Hello. First of all, thank you very much for the development and sharing of the synthetic control method in Python. I was just checking how the ATT is estimated and there is an error in the order of the difference (base.py, line 125): the gaps (for the ATT) should be estimated as "ts_synthetic - Z1" (not "Z1 - ts_synthetic"). Taking the "base.py" file just as it is, returns the ATT with the wrong sign.

**Comment by sdfordham** [comment]
E.g. say the outcome for the treated unit after treatment is 10 (Z0 = 10) and the outcome for the (synthetic) control after the treatment time is 5 (ts_synthetic=5) then you say that att should be ts_synthetic - Z1 = 5 - 10 = -5?

**Comment by arasala** [comment]
My apologies, I just got confused with notation. You are correct. ATT is "Z1 - ts_synthetic".

**Comment by sdfordham** [comment]
No problem, all good.
