### ISSUE TITLE
 seed

### ISSUE THREAD

**Issue by MJ-Hon** [sdfordham/pysyncon#66]
Hello

I am using your package for analysis and it seems to be very good. Thank you. 
However, I have a question.
There are differences in the analysis results each time I rerun the code in Visual Studio Code (VSC). Is there a way to specify a seed?

Much appreciated!

**Comment by sdfordham** [comment]
Can you post your code? This should not be possible as the optimization methods available do not have a random aspect to them.

**Comment by sdfordham** [comment]
Your code looks fine. It is surprising but I would guess that it is machine-precision related involving inverting the data matrix, are the numbers involved in your data very large or very small? It may help to try fixing some of the parameters in the BFGS case, you can provide more arguments to the minimize function by using `optim_options`. You can try playing around with the values e.g.

```python
synth.fit(
    dataprep=dataprep,
    optim_method="BFGS",
    optim_initial="equal",
    optim_options={"gtol": 1e-3, "xrtol": 1e-5, "c1": 0.1, "c2": 0.2}
)
```

The options available in the BFGS case are outlined https://docs.scipy.org/doc/scipy/reference/optimize.minimize-bfgs.html.

**Comment by MJ-Hon** [comment]
The number of control groups is 24, and the analysis period is from 2008 to 2021. The intervention year is 2013. The same phenomenon still appears, but thank you sincerely for your advice. I will review the document you provided.
